version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inforadar-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inforadar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inforadar-network

  client-frontend:
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
    container_name: inforadar-client-frontend
    ports:
      - "3000:3000"
    depends_on:
      - client-backend
    networks:
      - inforadar-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://client-backend:3001/api/v1

  client-backend:
    build:
      context: ./client/backend
      dockerfile: Dockerfile
    container_name: inforadar-client-backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - inforadar-network
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=inforadar
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}

  staff-frontend:
    build:
      context: ./staff/frontend
      dockerfile: Dockerfile
    container_name: inforadar-staff-frontend
    ports:
      - "3002:3000"
    depends_on:
      - staff-backend
    networks:
      - inforadar-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://staff-backend:3003/api/v1

  staff-backend:
    build:
      context: ./staff/backend
      dockerfile: Dockerfile
    container_name: inforadar-staff-backend
    ports:
      - "3003:3001"
    depends_on:
      - postgres
    networks:
      - inforadar-network
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=inforadar
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: inforadar-crawler
    depends_on:
      - client-backend
      - staff-backend
    networks:
      - inforadar-network
    environment:
      - NODE_ENV=development
      - CLIENT_API_URL=http://client-backend:3001/api/v1
      - STAFF_API_URL=http://staff-backend:3003/api/v1
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}

networks:
  inforadar-network:
    driver: bridge

volumes:
  postgres_data:
